#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mv /app/data /tmp/data

if [[ ! -f "/data/yaml/bot.yml" ]]; then
    echo "[NOTICE] Bot data not found in config folder, creating this folder and copying data"
    mv /tmp/data/ /data/yaml
fi

ln -s /data/yaml /app/data

chown -R app:app \
    /app \
    /config \
    /data \
    /app/data
