#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mv /app/data /tmp/data

if [[ ! -f "/data/bot/bot.yml" ]]; then
    echo "[NOTICE] Bot data not found in /data/yaml folder, creating this folder and copying data"
    mv /tmp/data/ /data/bot
fi

ln -s /data/bot /app/data

chown -R app:app \
    /app \
    /config \
    /data \
    /app/data
