name: Build nadekobot container

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      nadekobotVersion:
        description: 'version of nadekobot format: 5.0.0'
        required: true
        type: string
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: d3lta/unraid-container-nadekobot
  NADEKOBOTVERSION: ${{ github.ref_name }}
  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push docker image using workflow_dispatch with nadekobot version ${{ inputs.nadekobotVersion }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: build-and-push-specific-ver-only
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64
          build-args: |
            NADEKOBOT_VERSION=${{ github.event.inputs.nadekobotVersion }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.nadekobotVersion }}
          push: true
          labels: |
            org.opencontainers.image.source=${{github.server_url}}/${{github.repository}}
            org.opencontainers.image.description=Discord Bot https://gitlab.com/Kwoth/nadekobot for unraid running nadekobot version: ${{ github.event.inputs.nadekobotVersion }}
            org.opencontainers.image.licenses=MIT

      - name: Build and push Docker image with nadekobot version ${{ env.NADEKOBOTVERSION }}
        if: github.event_name != 'workflow_dispatch'
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64
          build-args: |
            NADEKOBOT_VERSION=${{ env.NADEKOBOTVERSION }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.NADEKOBOTVERSION }}
          push: true
          labels: |
            org.opencontainers.image.source=${{github.server_url}}/${{github.repository}}
            org.opencontainers.image.description=Discord Bot https://gitlab.com/Kwoth/nadekobot for unraid running nadekobot version: ${{ env.NADEKOBOTVERSION }}
            org.opencontainers.image.licenses=MIT
