name: Check and create releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

permissions:
  contents: write
  
jobs:
  check:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: "Set latest release version"
        id: latest
        run: echo "version=$(curl https://gitlab.com/Kwoth/nadekobot/-/releases.json | jq -r ".[0].tag")" >> "$GITHUB_OUTPUT"
        
      - name: "Check if newer version is available"
        uses: actions/github-script@v7
        env:
          INPUT_LATEST: ${{ steps.latest.outputs.version }}
        with:
            script: |
                  const getLatestRelease = await github.rest.repos.getLatestRelease({
                    owner: context.repo.owner,
                    repo: context.repo.repo
                  });
                  
                  const current = getLatestRelease.data.tag_name;
                  const latest = core.getInput('latest');
                  console.log("current", current, "latest", latest);
                  console.log(typeof(current), typeof(latest));

                  if(!current || !latest) {
                    console.log(`Input values: `, current, latest);
                    core.setFailed(1);
                    process.exit();
                  }
                  
                  const newerAvailable = () => {
                    // 0 equal, 1 a>b, -1 b>a
                    const update = (current.localeCompare(latest, undefined, { numeric: true, sensitivity: 'base' }) == -1)
                    console.log(update);
                    return update
                  };
                  
                  if(!newerAvailable) {
                    console.log(`No newer version available`);
                    return;
                  };
                  
                  try {
                      github.rest.reactions.createForRelease({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        release_id: `${latest}`,
                        content: `https://gitlab.com/Kwoth/nadekobot/-/tags/${latest}`
                      });
                    } catch(e) { console.log(`Failed to create release`) }
                  
              
